repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    - id: check-yaml
    - id: end-of-file-fixer
    - id: trailing-whitespace
  - repo: local
    hooks:
    - id: commitizen
      name: commitizen check
      language: python
      stages: [commit-msg]
      entry: .venv/bin/cz check --allow-abort --commit-msg-file
    - id: black
      name: black
      language: python
      types: [python]
      require_serial: true
      entry: .venv/bin/black
    - id: isort
      name: isort
      language: python
      types: [python]
      require_serial: true
      entry: .venv/bin/isort --filter-files
    - id: flake8
      name: flake8
      language: python
      types: [python]
      require_serial: true
      entry: .venv/bin/flake8
    - id: pyright
      name: pyright
      language: node
      types: [python]
      additional_dependencies: ["pyright@1.1.317"]
      entry: pyright
