name: main

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Bump version and create changelog with commitizen
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and create changelog
        uses: commitizen-tools/commitizen-action@0.18.0
        with:
          github_token: ${{ secrets.PAT }}
  publish:
    needs: bump-version
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Build and release to pypi
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
        with:
          install-dependencies: 'false'
      - name: Publish to pypi
        run: poetry publish --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
  documentation:
    runs-on: ubuntu-latest
    name: Build sphinx docs and publish them
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        uses: ./.github/actions/setup
      - name: Build docs
        run: poetry run poe docgen
      - name: Deploy with github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
