name: main

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Bump version and create changelog with commitizen
    steps:
      - name: Check out
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Bump version and create changelog
        uses: commitizen-tools/commitizen-action@0.18.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
  publish:
    needs: bump-version
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Build and release to pypi
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Use poetry
        uses: ./.github/actions/poetry
      - name: Publish to pypi
        run: poetry publish --dry-run --build --username __token__ --password ${{ secrets.PYPI_TOKEN }}
  documentation:
    needs: bump-version
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    name: Build sphinx docs and publish them
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Use poetry
        uses: ./.github/actions/poetry
      - name: Install requirements for sphinx autodoc
        run: |
          poetry export -f requirements.txt --output docs/requirements.txt && \
          pip install sphinx-rtd-theme
      - name: Build and Commit
        uses: sphinx-notes/pages@master
        with:
          documentation_path: docs
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
      - name: Back to original branch
        run: git checkout $GITHUB_REF
