name: testing

on:
  push:

jobs:
  linting:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v27
      - name: Run pre-commit
        run: nix develop --impure --command bash -c 'pre-commit run --all-files'
  testing:
    name: Test against Keycloak
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.12"]
        keycloak-version:
          [
            "18.0",
            "19.0",
            "20.0",
            "21.1",
            "22.0",
            "23.0",
            "24.0",
            "25.0",
            "26.0",
          ]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests
        run: KEYCLOAK_VERSION=${{ matrix.keycloak-version }} uv run --python ${{ steps.setup-python.outputs.python-path }} pytest
