name: testing

on:
  push:

jobs:
  linting:
    name: Run pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v27
      - name: Run pre-commit
        run: nix develop --impure --command bash -c 'pre-commit run --all-files'
  testing:
    name: Test against Keycloak
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix:
    #     python-version: ["3.9", "3.10", "3.11"]
    #     keycloak-version: ["18.0", "19.0", "20.0", "21.1"]
    steps:
      - name: Check out
        uses: actions/checkout@v4
      - name: Install nix
        uses: cachix/install-nix-action@v27
      - name: Run tests
        run: nix develop --impure --command bash -c 'pytest'
